/**
 * Run once: node fetch-repos.mjs
 * Fetches all public repos for anasbalochh from GitHub and rewrites src/data/projects.js
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GITHUB_USER = 'anasbalochh';

// ── 1. Fetch all repos (handles pagination) ──────────────────────────────────
async function fetchAllRepos() {
  const repos = [];
  let page = 1;
  while (true) {
    const res = await fetch(
      `https://api.github.com/users/${GITHUB_USER}/repos?per_page=100&sort=updated&page=${page}`,
      { headers: { 'User-Agent': 'msak-it-hub-fetcher', Accept: 'application/vnd.github.v3+json' } }
    );
    if (!res.ok) throw new Error(`GitHub API error: ${res.status} ${res.statusText}`);
    const batch = await res.json();
    if (!batch.length) break;
    repos.push(...batch);
    page++;
  }
  return repos;
}

// ── 2. Map to the site's project shape ───────────────────────────────────────
function mapRepo(r, index) {
  const year = new Date(r.pushed_at || r.created_at).getFullYear().toString();
  const tags = [];
  if (r.language) tags.push(r.language);
  if (r.topics?.length) tags.push(...r.topics.slice(0, 3));

  // mark recent or starred repos as featured (first 6 by recency)
  const featured = index < 6;

  return {
    name: r.name.replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    repo: r.name,
    year,
    desc: r.description || `A ${r.language || 'software'} project.`,
    tags: [...new Set(tags)].slice(0, 4),
    github: r.html_url,
    live: r.homepage || null,
    featured,
    image: null, // add your screenshot path here, e.g. '/projects/my-app.png'
  };
}

// ── 3. Write projects.js ──────────────────────────────────────────────────────
function toJS(projects) {
  const lines = projects.map((p) => {
    const tagsStr = JSON.stringify(p.tags);
    return `  {
    name: ${JSON.stringify(p.name)},
    repo: ${JSON.stringify(p.repo)},
    year: ${JSON.stringify(p.year)},
    desc: ${JSON.stringify(p.desc)},
    tags: ${tagsStr},
    github: ${JSON.stringify(p.github)},
    live: ${p.live ? JSON.stringify(p.live) : 'null'},
    featured: ${p.featured},
    image: null, // drop screenshot in /public/projects/ and set path here
  }`;
  });

  return `// Auto-generated by fetch-repos.mjs — re-run to refresh.
export const githubUser = {
  login: ${JSON.stringify(GITHUB_USER)},
  url: 'https://github.com/${GITHUB_USER}',
};

export const projects = [
${lines.join(',\n')}
];
`;
}

// ── Run ───────────────────────────────────────────────────────────────────────
console.log(`Fetching repos for ${GITHUB_USER}...`);
const repos = await fetchAllRepos();
console.log(`Found ${repos.length} repos.`);

const projects = repos.map(mapRepo);
const outPath = join(__dirname, 'src', 'data', 'projects.js');
writeFileSync(outPath, toJS(projects), 'utf8');
console.log(`✓ Written to ${outPath}`);
